description = "Base builder for Heroku-18 stack, based on ubuntu:18.04 base image"

[stack]
  id = "heroku-18"
  build-image = "koyeb/pack:18-build"
  run-image = "koyeb/pack:18"

[lifecycle]
  version = "0.14.0"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:06938365d0bb9c2b9e3d54b50331161541a4666e2fdb14b4880c9ae95d07b2b7"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack@sha256:02a26d364465a567782806effa2afbf4b992a1e15453bb8e62c5da27118dc7e6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:c913b5581cd8a935058f680e6de6b7d9fe66237c379dfddd24c2267c3f41c9ba"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack@sha256:3eeb3773cdbd29d4fb0d578f7781fe8c525de73593480e2740b7143262e5bef5"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:1.0.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.3.1&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "koyeb/nodejs"
  uri = "docker://koyeb/nodejs-buildpack@sha256:a909b018c78ddc584d4398806e45369ca28c1f77c269019c70dee98f5c4bcb18"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-nodejs-function-buildpack@sha256:7c7e4453ff62639bd2044001c0f504092c53ecff5b3a720adef7866611e5dea7"

[[buildpacks]]
  id = "koyeb/custom"
  uri = "docker://koyeb/buildpack-custom"

[[buildpacks]]
  id = "koyeb/custom-nodejs"
  uri = "docker://koyeb/buildpack-custom-nodejs"

[[order]]

  [[order.group]]
    id = "heroku/ruby"
    version = "0.1.3"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/scala"
    version = "0.0.92"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/php"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "1.0.1"
    optional = true

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/nodejs-function"
    version = "0.9.3"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.30"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true

[[order]]

  [[order.group]]
    id = "koyeb/custom-nodejs"
    version = "0.1.0"
    optional = true

  [[order.group]]
    id = "koyeb/nodejs"
    version = "0.5.1"

[[order]]

  [[order.group]]
    id = "heroku/java"
    version = "0.5.0"

  [[order.group]]
    id = "koyeb/custom"
    version = "0.1.0"
    optional = true
